# Generated by Django 5.0.6 on 2024-06-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_count',
            field=models.IntegerField(default=0),
        ),
    ]
